/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assembler;

import datapath.*;
import java.awt.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ramak
 */
public class NewJFrame extends javax.swing.JFrame {

    String filename;
    String filedirectory;
    boolean firstsave = false;
    String outputfile;
    String dir;
    String file;
    public primary_memory memory = new primary_memory();
    boolean pipelined = false;
    boolean data_forwarding = false;
    boolean disable_writing_to_registers = false;
    boolean disable_writing_to_pipelined_regs = false;
    boolean watch_pipline_reg = false;
    boolean stall_decode = false;
    boolean b1 = false;
    boolean b2 = false;
    boolean b3 = false;
    boolean b4 = false;
    int current_address = 0x00000000;
    Object[][] reg = new Object[][]{
        {"x0", 0},
        {"x1", 0},
        {"x2", memory.register[2]},
        {"x3", memory.register[3]},
        {"x4", 0},
        {"x5", 0},
        {"x6", 0},
        {"x7", 0},
        {"x8", 0},
        {"x9", 0},
        {"x10", 0},
        {"x11", 0},
        {"x12", 0},
        {"x13", 0},
        {"x14", 0},
        {"x15", 0},
        {"x16", 0},
        {"x17", 0},
        {"x18", 0},
        {"x19", 0},
        {"x20", 0},
        {"x21", 0},
        {"x22", 0},
        {"x23", 0},
        {"x24", 0},
        {"x25", 0},
        {"x26", 0},
        {"x27", 0},
        {"x28", 0},
        {"x29", 0},
        {"x30", 0},
        {"x31", 0},};
    String[] column = new String[]{
        "Register", "Value"
    };

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(20);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(20);
        jTable2.getColumnModel().getColumn(3).setPreferredWidth(20);
        jTable2.getColumnModel().getColumn(4).setPreferredWidth(20);
    }

    //pagination of memory table based on address
    void setMemoryTable(int address) {
        current_address = address;
        address = address - 40;
        for (int i = jTable2.getRowCount() - 1; i >= 0; i--) {
            if (address >= 0 && address < 0x7FFFFFF0) {
                jTable2.setValueAt(String.format("0x%08X", address), i, 0);
                for (int j = 0; j < 4; j++) {
                    String temp = primary_memory.mem.getOrDefault(address + j, "0");
                    int temp1 = Integer.parseInt(temp, 2);
                    jTable2.setValueAt(temp1, i, j + 1);

                }
            } else {
                for (int j = 0; j < 5; j++) {
                    jTable2.setValueAt(null, i, j);
                }
            }
            address = address + 4;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        Build = new javax.swing.JButton();
        Run = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cache_size = new javax.swing.JLabel();
        block_size = new javax.swing.JLabel();
        IColdMiss = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ICapacityMiss = new javax.swing.JTextField();
        no_sets = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NSets = new javax.swing.JTextField();
        tCacheSize = new javax.swing.JTextField();
        c_access = new javax.swing.JLabel();
        ITotalAccess = new javax.swing.JTextField();
        tBlockSize = new javax.swing.JTextField();
        instruction_cache_type = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IConflictMiss = new javax.swing.JTextField();
        ITotalMiss = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ComboIType = new javax.swing.JComboBox<>();
        ComboDType = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        DCapacityMiss = new javax.swing.JTextField();
        DColdMiss = new javax.swing.JTextField();
        DTotalAccess = new javax.swing.JTextField();
        c_access1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        DTotalMiss = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        DConflictMiss = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        pipeline = new javax.swing.JToggleButton();
        jLabel15 = new javax.swing.JLabel();
        pipeline1 = new javax.swing.JToggleButton();
        pipeline2 = new javax.swing.JToggleButton();
        pipeline3 = new javax.swing.JToggleButton();
        SdisableR = new javax.swing.JToggleButton();
        Sdata_forward = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        MenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        New = new javax.swing.JMenuItem();
        Open = new javax.swing.JMenuItem();
        Save = new javax.swing.JMenuItem();
        SaveAs = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        Cut = new javax.swing.JMenuItem();
        Paste = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextArea1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setRollover(true);
        jToolBar1.setToolTipText("");
        jToolBar1.setAlignmentY(0.5F);
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToolBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jToolBar1.setMargin(new java.awt.Insets(1, 100, 100, 10));

        Build.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Build.setText("Build");
        Build.setFocusable(false);
        Build.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Build.setMargin(new java.awt.Insets(2, 2, 2, 4));
        Build.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Build.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuildActionPerformed(evt);
            }
        });
        jToolBar1.add(Build);

        Run.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Run.setText("Run");
        Run.setFocusable(false);
        Run.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Run.setMargin(new java.awt.Insets(2, 4, 2, 4));
        Run.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunActionPerformed(evt);
            }
        });
        jToolBar1.add(Run);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            reg,column
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jScrollPane3.setViewportView(jTable1);

        jTabbedPane1.addTab("REGISTERS", jScrollPane3);

        jTable2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable2.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

                {"0x00000028", 0, 0, 0, 0},
                {"0x00000024", 0, 0, 0, 0},
                {"0x00000020", 0, 0, 0, 0},
                {"0x0000001C", 0, 0, 0, 0},
                {"0x00000018", 0, 0, 0, 0},
                {"0x00000014", 0, 0, 0, 0},
                {"0x00000010", 0, 0, 0, 0},
                {"0x0000000C", 0, 0, 0, 0},
                {"0x00000008", 0, 0, 0, 0},
                {"0x00000004", 0, 0, 0, 0},
                {"0x00000000", 0, 0, 0, 0},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ADDRESS", "+0", "+1", "+2", "+3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable2.setRowHeight(35);
        jScrollPane4.setViewportView(jTable2);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("JUMP TO");

        jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField11FocusLost(evt);
            }
        });
        jTextField11.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextField11PropertyChange(evt);
            }
        });
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField11KeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("UP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("ADDRESS");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Text", "Data", "Heap", "Stack" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setText("DOWN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("MEMORY", jPanel3);

        cache_size.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cache_size.setText("Cache Size in Words");

        block_size.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        block_size.setText("Block Size");

        IColdMiss.setEditable(false);
        IColdMiss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        IColdMiss.setText("0");
        IColdMiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IColdMissActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("CACHE INFORMATION");

        ICapacityMiss.setEditable(false);
        ICapacityMiss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ICapacityMiss.setText("0");

        no_sets.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no_sets.setText("No Of Sets");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Total Miss");

        NSets.setEditable(false);
        NSets.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NSets.setText("0");

        tCacheSize.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tCacheSize.setText("2");

        c_access.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c_access.setText("Total access");

        ITotalAccess.setEditable(false);
        ITotalAccess.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ITotalAccess.setText("0");

        tBlockSize.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tBlockSize.setText("2");

        instruction_cache_type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instruction_cache_type.setText("Instr Cache Type");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Conflict Miss");

        IConflictMiss.setEditable(false);
        IConflictMiss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        IConflictMiss.setText("0");

        ITotalMiss.setEditable(false);
        ITotalMiss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ITotalMiss.setText("0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cold Miss");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Capacity Miss");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Data Cache type");

        ComboIType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboIType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DM", "FA", "SA" }));
        ComboIType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboITypeActionPerformed(evt);
            }
        });

        ComboDType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboDType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DM", "FA", "SA" }));
        ComboDType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboDTypeActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("INSTRUCTION CACHE");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("DATA CACHE");

        DCapacityMiss.setEditable(false);
        DCapacityMiss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DCapacityMiss.setText("0");

        DColdMiss.setEditable(false);
        DColdMiss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DColdMiss.setText("0");
        DColdMiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DColdMissActionPerformed(evt);
            }
        });

        DTotalAccess.setEditable(false);
        DTotalAccess.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DTotalAccess.setText("0");

        c_access1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c_access1.setText("Total access");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Capacity Miss");

        DTotalMiss.setEditable(false);
        DTotalMiss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DTotalMiss.setText("0");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Cold Miss");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Conflict Miss");

        DConflictMiss.setEditable(false);
        DConflictMiss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DConflictMiss.setText("0");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Total Miss");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(block_size, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(instruction_cache_type, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(no_sets, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cache_size, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboIType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tBlockSize)
                            .addComponent(tCacheSize)
                            .addComponent(ComboDType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NSets)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(c_access, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel6))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ITotalAccess, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ITotalMiss, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(IColdMiss, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(IConflictMiss, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ICapacityMiss, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(c_access1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel14))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DTotalAccess, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DTotalMiss, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DColdMiss, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DConflictMiss, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DCapacityMiss, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(44, 44, 44)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCacheSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cache_size, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tBlockSize, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(block_size, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instruction_cache_type, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboIType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboDType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(no_sets, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NSets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ITotalAccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_access, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ITotalMiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IColdMiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(IConflictMiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ICapacityMiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DTotalAccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_access1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DTotalMiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DColdMiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(DConflictMiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(DCapacityMiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CACHE", jPanel2);

        pipeline.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pipeline.setText("PIPELINE");
        pipeline.setFocusable(false);
        pipeline.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pipeline.setMargin(new java.awt.Insets(2, 4, 2, 4));
        pipeline.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pipeline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pipelineActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("PIPELINE KNOBS");

        pipeline1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pipeline1.setText("STALL DECODE");
        pipeline1.setFocusable(false);
        pipeline1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pipeline1.setMargin(new java.awt.Insets(2, 4, 2, 4));
        pipeline1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pipeline1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pipeline1ActionPerformed(evt);
            }
        });

        pipeline2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pipeline2.setText("WATCH PIPELINED REGISTERS");
        pipeline2.setFocusable(false);
        pipeline2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pipeline2.setMargin(new java.awt.Insets(2, 4, 2, 4));
        pipeline2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pipeline2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pipeline2ActionPerformed(evt);
            }
        });

        pipeline3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pipeline3.setText("WRITE TO PIPILINED REGISTERS");
        pipeline3.setFocusable(false);
        pipeline3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pipeline3.setMargin(new java.awt.Insets(2, 4, 2, 4));
        pipeline3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pipeline3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pipeline3ActionPerformed(evt);
            }
        });

        SdisableR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SdisableR.setText("WRITE TO REGISTERS");
        SdisableR.setFocusable(false);
        SdisableR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SdisableR.setMargin(new java.awt.Insets(2, 4, 2, 4));
        SdisableR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SdisableR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SdisableRActionPerformed(evt);
            }
        });

        Sdata_forward.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Sdata_forward.setText("DATA FORWARDING");
        Sdata_forward.setFocusable(false);
        Sdata_forward.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sdata_forward.setMargin(new java.awt.Insets(2, 4, 2, 4));
        Sdata_forward.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Sdata_forward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sdata_forwardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pipeline))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pipeline1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pipeline2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pipeline3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(SdisableR))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Sdata_forward)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(15, 15, 15)
                .addComponent(pipeline, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(Sdata_forward, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(SdisableR, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(pipeline3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(pipeline2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(pipeline1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(477, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PIPELINE", jPanel5);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane5.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        New.setText("New");
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });
        jMenu1.add(New);

        Open.setText("Open");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        jMenu1.add(Open);

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jMenu1.add(Save);

        SaveAs.setText("Save As");
        SaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsActionPerformed(evt);
            }
        });
        jMenu1.add(SaveAs);

        MenuBar.add(jMenu1);

        Edit.setText("Edit");

        Cut.setText("Cut");
        Edit.add(Cut);

        Paste.setText("Paste");
        Edit.add(Paste);

        MenuBar.add(Edit);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // MenuBar.add(jButton1);
    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        setTitle(filename);

    }//GEN-LAST:event_NewActionPerformed

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        // TODO add your handling code here:
        FileDialog fileDialog = new FileDialog(NewJFrame.this, "Open File", FileDialog.LOAD);
        fileDialog.setVisible(true);
        if (fileDialog.getFile() != null) {
            filename = fileDialog.getDirectory() + fileDialog.getFile();
            setTitle(filename);
        }
        try {
            BufferedReader reader = new BufferedReader(new FileReader(filename));
            StringBuilder sb = new StringBuilder();
            String line = null;
            while ((line = reader.readLine()) != null) {
                sb.append(line).append("\n");
                jTextArea1.setText(sb.toString());

            }
            reader.close();
        } catch (IOException e) {
            System.out.println("File not found");
        }
    }//GEN-LAST:event_OpenActionPerformed

    private void SaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsActionPerformed
        FileDialog fileDialog = new FileDialog(NewJFrame.this, "Save File", FileDialog.SAVE);
        fileDialog.setVisible(true);
        if (fileDialog.getFile() != null) {
            filename = fileDialog.getDirectory() + fileDialog.getFile();
            file = fileDialog.getFile();
            dir = fileDialog.getDirectory();
            setTitle(filename);
        }
        try {
            FileWriter filewriter = new FileWriter(filename);
            String content = jTextArea1.getText();
            content = content.replaceAll("(?!\\r)\\n", "\r\n");
            filewriter.write(content);
            setTitle(filename);
            filewriter.flush();
            filewriter.close();
        } catch (IOException e) {
            System.out.println("File not found");
        }
        firstsave = true;
    }//GEN-LAST:event_SaveAsActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        if (firstsave == false) {
            SaveAsActionPerformed(evt);
            // firstsave = true;
        }
        try {
            FileWriter filewriter = new FileWriter(filename);
            String content = jTextArea1.getText();
            content = content.replaceAll("(?!\\r)\\n", "\r\n");
            filewriter.write(content);
//filewriter.write(jTextArea1.getText());
            setTitle(filename);
            filewriter.close();
            filewriter.close();
        } catch (IOException e) {
            System.out.println("File not found");
        }


    }//GEN-LAST:event_SaveActionPerformed

    private void BuildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuildActionPerformed
        // TODO add your handling code here:
        SaveActionPerformed(evt);
        int a1 = Integer.parseInt(tCacheSize.getText());
        int a2 = Integer.parseInt(tBlockSize.getText());
        int a3 = ComboIType.getSelectedIndex();
        int a4 = ComboDType.getSelectedIndex();
        int a5 = Integer.parseInt(NSets.getText());

        memory.set_primary_memory(a1, a2, a3, a4, a5);
        assembler obj = new assembler();
        try {
            obj.assemble(filename, memory);
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        // PrintWriter p=null;
        //creating output filename
        int temp = file.indexOf('.');
        outputfile = dir + file.substring(0, temp) + ".mc";
        PrintWriter p;

        try {
            p = new PrintWriter(new FileOutputStream(outputfile, false));
            for (int i = 0; i < obj.instructions_temp.length; i++) {
                Long decimal = Long.parseLong(obj.instructions_temp[i].binary, 2);
                // String hexStr = Integer.toString(decimal, 16);
                // System.out.println(decimal.toHexString());
                // System.out.println(String.format("0x%08X", decimal));
                // PrintWriter writer = nul
                p.println(String.format("0x%08X", decimal));

                // p.flush();
            }
            // p.println(assembler.instructions_temp.length);
            p.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextArea3.setEditable(true);
        try {
            BufferedReader reader = new BufferedReader(new FileReader(outputfile));
            StringBuilder sb = new StringBuilder();
            String line = null;
            while ((line = reader.readLine()) != null) {
                sb.append(line).append("\n");
                jTextArea3.setText(sb.toString());

            }
            reader.close();
        } catch (IOException e) {
            System.out.println("File not found");
        }
        jTextArea3.setEditable(false);
    }//GEN-LAST:event_BuildActionPerformed

    private void RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunActionPerformed
        // TODO add your handling code here:
        //String a=jTextField1.toString();
        BuildActionPerformed(evt);
        File file = new File(outputfile);

        int mem_index = 0;
        try {

            BufferedReader br = new BufferedReader(new FileReader(file));
            String line;
            //System.out.println("No input");
            while ((line = br.readLine()) != null) {
                //System.out.println(line);
                long itemp = Long.parseLong(line.substring(2), 16);
                String bin_line = Long.toBinaryString(itemp);
                String temp = "";
                for (int i = 0; i < 32 - bin_line.length(); i++) {
                    temp = temp + "0";
                }
                memory.storewordstr(mem_index, temp + bin_line);
                //System.out.println(mem.loadword(mem_index)+"p");
                mem_index = mem_index + 4;

            }
        } catch (Exception e) {
            System.out.println(e);
        }
        datapath dat = new datapath();

        dat.run(memory, pipelined,
                data_forwarding,
                disable_writing_to_registers,
                disable_writing_to_pipelined_regs,
                watch_pipline_reg,
                 stall_decode
        );
        ITotalAccess.setText(Integer.toString(memory.i_cache.access));
        ITotalMiss.setText(Integer.toString(memory.i_cache.capacity_miss + memory.i_cache.cold_miss + memory.i_cache.conflict_miss));
        IColdMiss.setText(Integer.toString(memory.i_cache.cold_miss));
        IConflictMiss.setText(Integer.toString(memory.i_cache.conflict_miss));
        ICapacityMiss.setText(Integer.toString(memory.i_cache.capacity_miss));
        DTotalAccess.setText(Integer.toString(memory.d_cache.access));
        DTotalMiss.setText(Integer.toString(memory.d_cache.capacity_miss + memory.d_cache.cold_miss + memory.d_cache.conflict_miss));
        DColdMiss.setText(Integer.toString(memory.d_cache.cold_miss));
        DConflictMiss.setText(Integer.toString(memory.d_cache.conflict_miss));
        DCapacityMiss.setText(Integer.toString(memory.d_cache.capacity_miss));
//System.out.println(memory.access);
        for (int i = 0; i < 32; i++) {
            if (i == 0) {
                reg[i][1] = 0;
            }
            reg[i][1] = memory.register[i];
        }
        jTable1.setModel(new DefaultTableModel(reg, column));
    }//GEN-LAST:event_RunActionPerformed

    private void pipelineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pipelineActionPerformed
        // TODO add your handling code here:
        pipelined = !pipelined;
    }//GEN-LAST:event_pipelineActionPerformed

    private void IColdMissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IColdMissActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IColdMissActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        current_address += 20;
        if (current_address <= 0x7FFFFFF0 && current_address > 0)
            setMemoryTable(current_address);
        else
            current_address -= 20;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        current_address -= 20;
        if (current_address >= 0x00000000)
            setMemoryTable(current_address);
        else
            current_address += 20;        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int temp = jComboBox1.getSelectedIndex();
        if (temp == 0) {
            setMemoryTable(0);
        }
        if (temp == 1) {
            setMemoryTable(0x10000000);
        }
        if (temp == 2)
            setMemoryTable(0x10007FE8);
        else if (temp == 3)
            setMemoryTable(0x7FFFFFF0);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField11FocusLost
        // TODO add your handling code here:
        String a = jTextField11.getText();
        if (a.isEmpty()) {
            return;
        }
        try {
            int b = Integer.parseInt(a, 16);
            setMemoryTable(b);
        } catch (NumberFormatException e) {
            return;
        }
        jTextField11.setText(null);
    }//GEN-LAST:event_jTextField11FocusLost

    private void jTextField11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11KeyPressed

    private void jTextField11PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextField11PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11PropertyChange

    private void DColdMissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DColdMissActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DColdMissActionPerformed

    private void ComboITypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboITypeActionPerformed
        if (ComboIType.getSelectedIndex() == 2)
            NSets.setEditable(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ComboITypeActionPerformed

    private void ComboDTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboDTypeActionPerformed
        // TODO add your handling code here:
        if (ComboIType.getSelectedIndex() == 2)
            NSets.setEditable(true);
    }//GEN-LAST:event_ComboDTypeActionPerformed

    private void pipeline1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pipeline1ActionPerformed
        // TODO add your handling code here:
        this.stall_decode = !this.stall_decode;
    }//GEN-LAST:event_pipeline1ActionPerformed

    private void pipeline2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pipeline2ActionPerformed
        this.watch_pipline_reg = !this.watch_pipline_reg;        // TODO add your handling code here:
    }//GEN-LAST:event_pipeline2ActionPerformed

    private void pipeline3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pipeline3ActionPerformed
        this.disable_writing_to_pipelined_regs = this.disable_writing_to_pipelined_regs;        // TODO add your handling code here:
    }//GEN-LAST:event_pipeline3ActionPerformed

    private void SdisableRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SdisableRActionPerformed
        this.disable_writing_to_registers = !this.disable_writing_to_registers;        // TODO add your handling code here:
    }//GEN-LAST:event_SdisableRActionPerformed

    private void Sdata_forwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sdata_forwardActionPerformed
        this.data_forwarding = !this.data_forwarding;        // TODO add your handling code here:
    }//GEN-LAST:event_Sdata_forwardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Build;
    private javax.swing.JComboBox<String> ComboDType;
    private javax.swing.JComboBox<String> ComboIType;
    private javax.swing.JMenuItem Cut;
    private javax.swing.JTextField DCapacityMiss;
    private javax.swing.JTextField DColdMiss;
    private javax.swing.JTextField DConflictMiss;
    private javax.swing.JTextField DTotalAccess;
    private javax.swing.JTextField DTotalMiss;
    private javax.swing.JMenu Edit;
    private javax.swing.JTextField ICapacityMiss;
    private javax.swing.JTextField IColdMiss;
    private javax.swing.JTextField IConflictMiss;
    private javax.swing.JTextField ITotalAccess;
    private javax.swing.JTextField ITotalMiss;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JTextField NSets;
    private javax.swing.JMenuItem New;
    private javax.swing.JMenuItem Open;
    private javax.swing.JMenuItem Paste;
    private javax.swing.JButton Run;
    private javax.swing.JMenuItem Save;
    private javax.swing.JMenuItem SaveAs;
    private javax.swing.JToggleButton Sdata_forward;
    private javax.swing.JToggleButton SdisableR;
    private javax.swing.JLabel block_size;
    private javax.swing.JLabel c_access;
    private javax.swing.JLabel c_access1;
    private javax.swing.JLabel cache_size;
    private javax.swing.JLabel instruction_cache_type;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel no_sets;
    private javax.swing.JToggleButton pipeline;
    private javax.swing.JToggleButton pipeline1;
    private javax.swing.JToggleButton pipeline2;
    private javax.swing.JToggleButton pipeline3;
    private javax.swing.JTextField tBlockSize;
    private javax.swing.JTextField tCacheSize;
    // End of variables declaration//GEN-END:variables
}
